"""
AGORA FM — Service Provider Seed Script
seed_providers.py

Run with:  python seed_providers.py
Creates agora_providers.db and populates it with 80 fictional service providers
(4 companies × 5 subcategories × 4 main categories + Electricity).
"""
from models import ServiceProvider, get_engine, create_tables
from sqlalchemy.orm import Session

# ── Seed data ────────────────────────────────────────────────────────────────
PROVIDERS = [

    # ═══════════════════════════════════════════════════════════════════════
    # FIRE
    # ═══════════════════════════════════════════════════════════════════════

    # Fire extinguisher servicing
    {
        "company_name":           "Redline Fire Safety Ltd",
        "address":                "14 Anvil Way, Sheffield, S3 8LT",
        "website":                "https://www.redlinefiresafety.co.uk",
        "email":                  "service@redlinefiresafety.co.uk",
        "telephone":              "0114 201 4490",
        "main_category":          "Fire",
        "subcategory":            "Fire extinguisher servicing",
        "service_description":    "Annual inspection, recharge and certification of all extinguisher types including CO2, powder, foam and wet chemical. BAFE-certified engineers. Full compliance report issued same day.",
        "pricing_amount":         "420.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/redline-fire-safety",
    },
    {
        "company_name":           "BlazeCare Services Ltd",
        "address":                "Unit 3, Thornton Industrial Estate, Bradford, BD1 2NQ",
        "website":                "https://www.blazecareservices.co.uk",
        "email":                  "info@blazecareservices.co.uk",
        "telephone":              "01274 889 321",
        "main_category":          "Fire",
        "subcategory":            "Fire extinguisher servicing",
        "service_description":    "Full extinguisher service covering inspection, discharge testing, re-filling and statutory labelling. Nationwide coverage. CHAS-accredited. Service records stored digitally on client portal.",
        "pricing_amount":         "380.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/blazecare-services",
    },
    {
        "company_name":           "Ignition Compliance Ltd",
        "address":                "22 Copper Road, Norwich, NR1 3BZ",
        "website":                "https://www.ignitioncompliance.co.uk",
        "email":                  "enquiries@ignitioncompliance.co.uk",
        "telephone":              "01603 774 882",
        "main_category":          "Fire",
        "subcategory":            "Fire extinguisher servicing",
        "service_description":    "Scheduled and emergency extinguisher servicing for commercial premises. All work carried out to BS 5306-3. Certificate of conformity issued on completion. Weekend appointments available.",
        "pricing_amount":         "395.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/ignition-compliance",
    },
    {
        "company_name":           "FireShield Maintenance Ltd",
        "address":                "8 Hallgate Business Park, Pontefract, WF8 1PQ",
        "website":                "https://www.fireshieldmaintenance.co.uk",
        "email":                  "bookings@fireshieldmaintenance.co.uk",
        "telephone":              "01977 663 120",
        "main_category":          "Fire",
        "subcategory":            "Fire extinguisher servicing",
        "service_description":    "Comprehensive extinguisher maintenance contracts for multi-site estates. Includes visual inspections, pressure tests and extended service. Compliant with BS EN 3. Instant digital reports.",
        "pricing_amount":         "450.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/fireshield-maintenance",
    },

    # Fire alarm maintenance
    {
        "company_name":           "Sentinel Alarm Systems Ltd",
        "address":                "45 Regent Crescent, Leicester, LE1 6WX",
        "website":                "https://www.sentinelalarmsystems.co.uk",
        "email":                  "contracts@sentinelalarmsystems.co.uk",
        "telephone":              "0116 278 5540",
        "main_category":          "Fire",
        "subcategory":            "Fire alarm maintenance",
        "service_description":    "Full fire alarm maintenance contracts covering bi-annual inspections, detector testing, panel servicing and fault resolution. NSI Gold approved. Compliant with BS 5839-1. 4-hour emergency response SLA.",
        "pricing_amount":         "890.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/sentinel-alarm-systems",
    },
    {
        "company_name":           "Clearbell Fire Protection Ltd",
        "address":                "30 Millfield Avenue, Preston, PR2 8ST",
        "website":                "https://www.clearbellfire.co.uk",
        "email":                  "service@clearbellfire.co.uk",
        "telephone":              "01772 441 900",
        "main_category":          "Fire",
        "subcategory":            "Fire alarm maintenance",
        "service_description":    "Preventive and reactive fire alarm maintenance for commercial and industrial premises. All major panel manufacturers supported. Quarterly reporting included. BAFE SP203-1 certificated contractor.",
        "pricing_amount":         "75.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/clearbell-fire-protection",
    },
    {
        "company_name":           "Apex Fire & Security Ltd",
        "address":                "Unit 9, Ashbourne Road, Derby, DE22 3FS",
        "website":                "https://www.apexfiresecurity.co.uk",
        "email":                  "maintenance@apexfiresecurity.co.uk",
        "telephone":              "01332 519 870",
        "main_category":          "Fire",
        "subcategory":            "Fire alarm maintenance",
        "service_description":    "Addressable and conventional fire alarm servicing. Includes panel firmware updates, zone testing, sounder checks and full compliance documentation. 24/7 monitoring available as add-on.",
        "pricing_amount":         "820.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/apex-fire-security",
    },
    {
        "company_name":           "SafeAlert Systems Ltd",
        "address":                "17 Bramblewood Court, Coventry, CV6 4PP",
        "website":                "https://www.safealertsystems.co.uk",
        "email":                  "info@safealertsystems.co.uk",
        "telephone":              "024 7661 3300",
        "main_category":          "Fire",
        "subcategory":            "Fire alarm maintenance",
        "service_description":    "Fire alarm maintenance tailored for multi-occupancy and mixed-use buildings. Full log book management, false alarm reduction reporting and liaison with local fire authority on request.",
        "pricing_amount":         "68.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/safealert-systems",
    },

    # Emergency lighting checks
    {
        "company_name":           "LuminaCheck Ltd",
        "address":                "55 Glasshouse Street, Nottingham, NG1 3LW",
        "website":                "https://www.luminacheck.co.uk",
        "email":                  "testing@luminacheck.co.uk",
        "telephone":              "0115 948 2201",
        "main_category":          "Fire",
        "subcategory":            "Emergency lighting checks",
        "service_description":    "Monthly flick-test monitoring, annual full-duration discharge test and battery replacement. Compliant with BS 5266-1. NICEIC-registered engineers. Electronic logbook and certificate provided after every visit.",
        "pricing_amount":         "360.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/luminacheck",
    },
    {
        "company_name":           "NightPath Electrical Services Ltd",
        "address":                "6 Foundry Lane, Wolverhampton, WV2 2BE",
        "website":                "https://www.nightpathelectrical.co.uk",
        "email":                  "enquiries@nightpathelectrical.co.uk",
        "telephone":              "01902 774 330",
        "main_category":          "Fire",
        "subcategory":            "Emergency lighting checks",
        "service_description":    "Routine and emergency lighting compliance checks including 1-hour and 3-hour battery tests. Fault rectification included in annual contract price. Suitable for schools, offices and retail environments.",
        "pricing_amount":         "30.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/nightpath-electrical",
    },
    {
        "company_name":           "BrightEscape Compliance Ltd",
        "address":                "12 Minster Gate, York, YO1 7HL",
        "website":                "https://www.brightescape.co.uk",
        "email":                  "service@brightescape.co.uk",
        "telephone":              "01904 551 200",
        "main_category":          "Fire",
        "subcategory":            "Emergency lighting checks",
        "service_description":    "Dedicated emergency lighting service covering exit signs, maintained and non-maintained luminaires. Full photometric testing on request. Compliant with BS EN 1838. Reports submitted within 24 hours.",
        "pricing_amount":         "395.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/brightescape-compliance",
    },
    {
        "company_name":           "EscapeLight Solutions Ltd",
        "address":                "Unit 4, Humber Bridge Industrial Park, Hull, HU13 0HH",
        "website":                "https://www.escapelightsolutions.co.uk",
        "email":                  "bookings@escapelightsolutions.co.uk",
        "telephone":              "01482 639 540",
        "main_category":          "Fire",
        "subcategory":            "Emergency lighting checks",
        "service_description":    "Emergency lighting inspection and testing across all building types. Includes emergency central battery system (CBS) maintenance. All works conform to current IET Wiring Regulations and BS 5266.",
        "pricing_amount":         "340.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/escapelight-solutions",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # WATER
    # ═══════════════════════════════════════════════════════════════════════

    # Legionella testing
    {
        "company_name":           "ClearWater Compliance Ltd",
        "address":                "3 Quayside Business Park, Newcastle upon Tyne, NE1 3DX",
        "website":                "https://www.clearwatercompliance.co.uk",
        "email":                  "testing@clearwatercompliance.co.uk",
        "telephone":              "0191 232 8840",
        "main_category":          "Water",
        "subcategory":            "Legionella testing",
        "service_description":    "UKAS-accredited Legionella water sampling and analysis. Hot and cold water system testing in line with L8 ACOP and HSG274. Results within 5 working days. Full written report and recommended actions provided.",
        "pricing_amount":         "195.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/clearwater-compliance",
    },
    {
        "company_name":           "AquaGuard Testing Ltd",
        "address":                "88 Dock Road, Liverpool, L3 4AE",
        "website":                "https://www.aquaguardtesting.co.uk",
        "email":                  "lab@aquaguardtesting.co.uk",
        "telephone":              "0151 709 5512",
        "main_category":          "Water",
        "subcategory":            "Legionella testing",
        "service_description":    "Quarterly and annual Legionella sampling programmes for commercial estates. Includes temperature monitoring, sampling, UKAS laboratory analysis and corrective action reports. Schematic drawings updated annually.",
        "pricing_amount":         "220.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/aquaguard-testing",
    },
    {
        "company_name":           "HydroSafe Systems Ltd",
        "address":                "19 Canal Wharf, Leeds, LS11 5PS",
        "website":                "https://www.hydrosafeuk.co.uk",
        "email":                  "info@hydrosafeuk.co.uk",
        "telephone":              "0113 244 7720",
        "main_category":          "Water",
        "subcategory":            "Legionella testing",
        "service_description":    "Legionella risk management including sampling, temperature monitoring and sentinel outlet checks. Accredited to ISO 17025. Suitable for healthcare, education and commercial premises. 24-hour emergency sampling available.",
        "pricing_amount":         "18.50",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/hydrosafe-systems",
    },
    {
        "company_name":           "PureLine Water Services Ltd",
        "address":                "Unit 7, Wilmslow Road, Manchester, M20 6RG",
        "website":                "https://www.purelinewater.co.uk",
        "email":                  "service@purelinewater.co.uk",
        "telephone":              "0161 434 9900",
        "main_category":          "Water",
        "subcategory":            "Legionella testing",
        "service_description":    "Legionella sampling, analysis and written risk assessment update service. Covers all water outlets including showers, taps, calorifiers and cooling towers. Frequency programmes tailored to risk profile.",
        "pricing_amount":         "240.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/pureline-water",
    },

    # Water tank cleaning
    {
        "company_name":           "TankClean Pro Ltd",
        "address":                "22 Station Road, Swindon, SN1 1DG",
        "website":                "https://www.tankcleanpro.co.uk",
        "email":                  "bookings@tankcleanpro.co.uk",
        "telephone":              "01793 512 200",
        "main_category":          "Water",
        "subcategory":            "Water tank cleaning",
        "service_description":    "Cold water storage tank (CWST) inspection and clean in accordance with BS 8558 and WRAS guidelines. Includes decontamination, chlorination dosing and post-clean sampling. Written report issued within 48 hours.",
        "pricing_amount":         "345.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/tankclean-pro",
    },
    {
        "company_name":           "AquaVault Services Ltd",
        "address":                "14 Ringway Industrial Estate, Coventry, CV2 1NF",
        "website":                "https://www.aquavaultservices.co.uk",
        "email":                  "enquiries@aquavaultservices.co.uk",
        "telephone":              "024 7644 8833",
        "main_category":          "Water",
        "subcategory":            "Water tank cleaning",
        "service_description":    "Full cleaning and disinfection of potable water storage tanks. Confined space trained operatives. Includes sediment removal, liner inspection, inlet/outlet valve checks and final water quality certificate.",
        "pricing_amount":         "370.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/aquavault-services",
    },
    {
        "company_name":           "Sterling Water Hygiene Ltd",
        "address":                "7 Wheatfield Road, Bristol, BS5 9RQ",
        "website":                "https://www.sterlingwaterhygiene.co.uk",
        "email":                  "team@sterlingwaterhygiene.co.uk",
        "telephone":              "0117 955 4410",
        "main_category":          "Water",
        "subcategory":            "Water tank cleaning",
        "service_description":    "Annual tank inspection and clean for commercial and residential estates. All operatives IPAF and confined space trained. Service includes pre and post-clean turbidity and bacteriological water testing.",
        "pricing_amount":         "30.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/sterling-water-hygiene",
    },
    {
        "company_name":           "BlueDepth Maintenance Ltd",
        "address":                "33 Quay Street, Portsmouth, PO1 2HH",
        "website":                "https://www.bluedepthmaintenance.co.uk",
        "email":                  "info@bluedepthmaintenance.co.uk",
        "telephone":              "023 9282 6640",
        "main_category":          "Water",
        "subcategory":            "Water tank cleaning",
        "service_description":    "Cold and hot water tank cleaning, inspection and disinfection. Tanks up to 45,000 litres serviced. Compliant with WRAS and HSG274 Part 2. Tank condition grading report and photographic evidence provided.",
        "pricing_amount":         "390.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/bluedepth-maintenance",
    },

    # Water hygiene monitoring
    {
        "company_name":           "Vivid Water Solutions Ltd",
        "address":                "5 Elm Park Industrial Estate, Chelmsford, CM2 0TD",
        "website":                "https://www.vividwatersolutions.co.uk",
        "email":                  "monitoring@vividwatersolutions.co.uk",
        "telephone":              "01245 333 780",
        "main_category":          "Water",
        "subcategory":            "Water hygiene monitoring",
        "service_description":    "Ongoing water hygiene monitoring programme including monthly temperature checks, quarterly sampling and annual risk assessment review. Electronic logbooks maintained and accessible via client portal 24/7.",
        "pricing_amount":         "65.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/vivid-water-solutions",
    },
    {
        "company_name":           "FlowSafe Compliance Ltd",
        "address":                "18 Orchard Business Centre, Maidstone, ME16 8PX",
        "website":                "https://www.flowsafecompliance.co.uk",
        "email":                  "contracts@flowsafecompliance.co.uk",
        "telephone":              "01622 780 450",
        "main_category":          "Water",
        "subcategory":            "Water hygiene monitoring",
        "service_description":    "Comprehensive water hygiene management covering Legionella control, TMV servicing, dead leg identification and outlet flushing programmes. Suitable for complex healthcare and education estates.",
        "pricing_amount":         "720.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/flowsafe-compliance",
    },
    {
        "company_name":           "WaterWatch Services Ltd",
        "address":                "11 Derwent Court, Derby, DE1 2NQ",
        "website":                "https://www.waterwatchservices.co.uk",
        "email":                  "info@waterwatchservices.co.uk",
        "telephone":              "01332 340 900",
        "main_category":          "Water",
        "subcategory":            "Water hygiene monitoring",
        "service_description":    "Monthly water hygiene site visits covering temperature monitoring, sentinel outlet testing, visual inspections and log book updates. Includes annual L8 risk assessment review and schematic update service.",
        "pricing_amount":         "58.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/waterwatch-services",
    },
    {
        "company_name":           "PureFlow Water Management Ltd",
        "address":                "25 Victoria Business Park, Northampton, NN1 5EA",
        "website":                "https://www.pureflowwm.co.uk",
        "email":                  "hygiene@pureflowwm.co.uk",
        "telephone":              "01604 630 770",
        "main_category":          "Water",
        "subcategory":            "Water hygiene monitoring",
        "service_description":    "Tailored water hygiene monitoring contracts for single and multi-site estates. Services include temperature logging, chlorine residual checks, TMV and showerhead maintenance and ACOP L8 compliance reporting.",
        "pricing_amount":         "780.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/pureflow-water-management",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # HVAC
    # ═══════════════════════════════════════════════════════════════════════

    # Air conditioning servicing
    {
        "company_name":           "CoolBreeze HVAC Ltd",
        "address":                "9 Meridian Way, Southampton, SO14 5QP",
        "website":                "https://www.coolbreezehvac.co.uk",
        "email":                  "service@coolbreezehvac.co.uk",
        "telephone":              "023 8033 4490",
        "main_category":          "HVAC",
        "subcategory":            "Air conditioning servicing",
        "service_description":    "Bi-annual air conditioning service and maintenance for split, multi-split and VRF systems. F-Gas certified engineers. Includes filter cleaning, refrigerant level check, coil inspection and performance report. All major brands covered.",
        "pricing_amount":         "580.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/coolbreeze-hvac",
    },
    {
        "company_name":           "ArcticAir Maintenance Ltd",
        "address":                "Unit 6, Kingsway Industrial Estate, Luton, LU1 1LP",
        "website":                "https://www.arcticairmaintenance.co.uk",
        "email":                  "contracts@arcticairmaintenance.co.uk",
        "telephone":              "01582 481 200",
        "main_category":          "HVAC",
        "subcategory":            "Air conditioning servicing",
        "service_description":    "Commercial air conditioning servicing including planned preventive maintenance and reactive callouts. REFCOM registered. F-Gas handling licence held. Service reports issued within 24 hours. 4-hour emergency response available.",
        "pricing_amount":         "52.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/arcticair-maintenance",
    },
    {
        "company_name":           "ThermalEdge Services Ltd",
        "address":                "14 Commerce Road, Stoke-on-Trent, ST4 2RT",
        "website":                "https://www.thermaledgeservices.co.uk",
        "email":                  "hvac@thermaledgeservices.co.uk",
        "telephone":              "01782 401 880",
        "main_category":          "HVAC",
        "subcategory":            "Air conditioning servicing",
        "service_description":    "Full air conditioning service contracts for offices, retail and industrial premises. Covers split and cassette units, fan coils and chilled water systems. Includes refrigerant leak checks in line with F-Gas Regulation (EU) 517/2014.",
        "pricing_amount":         "620.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/thermaledge-services",
    },
    {
        "company_name":           "Ventus Climate Control Ltd",
        "address":                "3 Riverside Park, Gloucester, GL1 1SL",
        "website":                "https://www.ventusclimatecontrol.co.uk",
        "email":                  "info@ventusclimatecontrol.co.uk",
        "telephone":              "01452 882 660",
        "main_category":          "HVAC",
        "subcategory":            "Air conditioning servicing",
        "service_description":    "Air conditioning planned maintenance covering all refrigerant types. Service includes electrical safety checks, drain clearance, UV lamp inspection and full system efficiency report. Emergency breakdown cover included.",
        "pricing_amount":         "560.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/ventus-climate-control",
    },

    # Boiler servicing
    {
        "company_name":           "HeatMaster Services Ltd",
        "address":                "7 Forge Road, Wolverhampton, WV14 9QR",
        "website":                "https://www.heatmasterservices.co.uk",
        "email":                  "boilers@heatmasterservices.co.uk",
        "telephone":              "01902 880 660",
        "main_category":          "HVAC",
        "subcategory":            "Boiler servicing",
        "service_description":    "Annual commercial boiler service by Gas Safe registered engineers. Covers all gas-fired boiler types including condensing, combination and pressurised systems. Includes flue analysis, controls check and gas tightness test.",
        "pricing_amount":         "195.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/heatmaster-services",
    },
    {
        "company_name":           "Celsius Mechanical Ltd",
        "address":                "24 Bricklayers Arms Road, Reading, RG1 7QN",
        "website":                "https://www.celsiusmechanical.co.uk",
        "email":                  "service@celsiusmechanical.co.uk",
        "telephone":              "0118 959 4400",
        "main_category":          "HVAC",
        "subcategory":            "Boiler servicing",
        "service_description":    "Planned preventive maintenance contracts for commercial boilers, plant rooms and pressurisation units. All works carried out by fully Gas Safe registered engineers. Emergency breakdown response within 4 hours.",
        "pricing_amount":         "18.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/celsius-mechanical",
    },
    {
        "company_name":           "FlamePoint Engineering Ltd",
        "address":                "41 Riverside Industrial Estate, Exeter, EX2 7LH",
        "website":                "https://www.flamepointengineering.co.uk",
        "email":                  "enquiries@flamepointengineering.co.uk",
        "telephone":              "01392 474 900",
        "main_category":          "HVAC",
        "subcategory":            "Boiler servicing",
        "service_description":    "Boiler servicing and gas safety inspection for commercial and industrial premises. Covers Ideal, Vaillant, Remeha and Hamworthy boilers. Service record updated in BMS where applicable. OFTEC oil boiler servicing also available.",
        "pricing_amount":         "210.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/flamepoint-engineering",
    },
    {
        "company_name":           "ThermoServ UK Ltd",
        "address":                "15 The Maltings, Cambridge, CB1 2LH",
        "website":                "https://www.thermoservuk.co.uk",
        "email":                  "maintenance@thermoservuk.co.uk",
        "telephone":              "01223 770 230",
        "main_category":          "HVAC",
        "subcategory":            "Boiler servicing",
        "service_description":    "Commercial boiler service contracts with 24/7 emergency cover. Gas Safe registered. Works include burner inspection, heat exchanger clean, safety valve test and combustion analysis. Digital service certificate issued.",
        "pricing_amount":         "185.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/thermoserv-uk",
    },

    # Ventilation system inspections
    {
        "company_name":           "AirFlow Inspections Ltd",
        "address":                "8 Gateway Industrial Park, Milton Keynes, MK11 3LR",
        "website":                "https://www.airflowinspections.co.uk",
        "email":                  "inspect@airflowinspections.co.uk",
        "telephone":              "01908 551 320",
        "main_category":          "HVAC",
        "subcategory":            "Ventilation system inspections",
        "service_description":    "Ductwork and ventilation system inspections to TR19 and BESA standards. Includes pre and post-clean inspection reports with photographic evidence. Kitchen extract, general ventilation and MVHR systems covered.",
        "pricing_amount":         "480.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/airflow-inspections",
    },
    {
        "company_name":           "DuctSafe Services Ltd",
        "address":                "5 Station Approach, Guildford, GU1 4UT",
        "website":                "https://www.ductsafeservices.co.uk",
        "email":                  "info@ductsafeservices.co.uk",
        "telephone":              "01483 770 110",
        "main_category":          "HVAC",
        "subcategory":            "Ventilation system inspections",
        "service_description":    "Ventilation hygiene inspections and ductwork surveys for commercial estates. TR19 compliant reports with grease deposit assessment. CHAS accredited. Inspection frequency recommended based on cooking activity level.",
        "pricing_amount":         "42.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/ductsafe-services",
    },
    {
        "company_name":           "PureAir Ventilation Ltd",
        "address":                "20 Commerce Way, Crawley, RH10 9QJ",
        "website":                "https://www.pureairventilation.co.uk",
        "email":                  "service@pureairventilation.co.uk",
        "telephone":              "01293 515 780",
        "main_category":          "HVAC",
        "subcategory":            "Ventilation system inspections",
        "service_description":    "Independent ventilation system inspection and hygiene audits. Covers AHUs, fan coils, fresh air handling units and supply/extract ductwork. TR19 grease assessment and IAQ measurement included.",
        "pricing_amount":         "510.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/pureair-ventilation",
    },
    {
        "company_name":           "CleanDuct Solutions Ltd",
        "address":                "32 Parkway Industrial Estate, Northampton, NN3 8RJ",
        "website":                "https://www.cleanductsolutions.co.uk",
        "email":                  "contracts@cleanductsolutions.co.uk",
        "telephone":              "01604 780 220",
        "main_category":          "HVAC",
        "subcategory":            "Ventilation system inspections",
        "service_description":    "Annual and bi-annual ventilation inspections in compliance with TR19 and HTM 03-01. Includes video survey, deposit thickness measurement, written inspection report and recommended clean frequency report.",
        "pricing_amount":         "460.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/cleanduct-solutions",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # RISK ASSESSMENTS
    # ═══════════════════════════════════════════════════════════════════════

    # General workplace risk assessments
    {
        "company_name":           "SafeSpace Consultancy Ltd",
        "address":                "10 New Street, Birmingham, B2 4EU",
        "website":                "https://www.safespaceconsultancy.co.uk",
        "email":                  "assessments@safespaceconsultancy.co.uk",
        "telephone":              "0121 643 8870",
        "main_category":          "Risk assessments",
        "subcategory":            "General workplace risk assessments",
        "service_description":    "Comprehensive workplace risk assessments covering manual handling, slips and trips, COSHH, lone working and general premises hazards. Written reports with RAG-rated action plans. NEBOSH-qualified assessors.",
        "pricing_amount":         "650.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/safespace-consultancy",
    },
    {
        "company_name":           "ClearRisk Solutions Ltd",
        "address":                "17 Exchange Square, Manchester, M2 7HA",
        "website":                "https://www.clearrisksolutions.co.uk",
        "email":                  "risk@clearrisksolutions.co.uk",
        "telephone":              "0161 833 2290",
        "main_category":          "Risk assessments",
        "subcategory":            "General workplace risk assessments",
        "service_description":    "On-site workplace risk assessment service for offices, warehouses and mixed-use estates. IOSH and NEBOSH certified consultants. Includes detailed report, photographic evidence and prioritised action log. Annual review available.",
        "pricing_amount":         "58.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/clearrisk-solutions",
    },
    {
        "company_name":           "Axiom Health & Safety Ltd",
        "address":                "6 St Andrew's Hill, Norwich, NR2 1AD",
        "website":                "https://www.axiomhealthsafety.co.uk",
        "email":                  "info@axiomhealthsafety.co.uk",
        "telephone":              "01603 660 450",
        "main_category":          "Risk assessments",
        "subcategory":            "General workplace risk assessments",
        "service_description":    "Tailored workplace risk assessments for all sectors. Services include general premises assessment, hazardous substance surveys and ergonomic evaluations. All assessors hold NEBOSH General Certificate as a minimum.",
        "pricing_amount":         "720.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/axiom-health-safety",
    },
    {
        "company_name":           "PinnacleHS Ltd",
        "address":                "30 Colmore Row, Birmingham, B3 2QD",
        "website":                "https://www.pinnaclehs.co.uk",
        "email":                  "consulting@pinnaclehs.co.uk",
        "telephone":              "0121 212 5540",
        "main_category":          "Risk assessments",
        "subcategory":            "General workplace risk assessments",
        "service_description":    "Full-spectrum health and safety risk assessment service. Suitable for SMEs and large multi-site estates. Includes hazard identification, risk rating, control measure recommendations and staff briefing on key findings.",
        "pricing_amount":         "680.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/pinnaclehs",
    },

    # DSE assessments
    {
        "company_name":           "WorkWell DSE Ltd",
        "address":                "22 High Holborn, London, WC1V 7DE",
        "website":                "https://www.workwelldse.co.uk",
        "email":                  "assessments@workwelldse.co.uk",
        "telephone":              "020 7421 6630",
        "main_category":          "Risk assessments",
        "subcategory":            "DSE assessments",
        "service_description":    "Display Screen Equipment assessments for office and home-based workers. Compliant with DSE Regulations 1992. Includes individual workstation checklist, posture and lighting assessment and written recommendations report.",
        "pricing_amount":         "35.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/workwell-dse",
    },
    {
        "company_name":           "ErgoCare Assessments Ltd",
        "address":                "14 Queens Road, Brighton, BN1 3WA",
        "website":                "https://www.ergocare-assessments.co.uk",
        "email":                  "dse@ergocare-assessments.co.uk",
        "telephone":              "01273 729 880",
        "main_category":          "Risk assessments",
        "subcategory":            "DSE assessments",
        "service_description":    "On-site and remote DSE assessments by qualified ergonomists. Covers standard workstations, laptops, hot desks and home office setups. Immediate equipment recommendations and follow-up support included.",
        "pricing_amount":         "390.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/ergocare-assessments",
    },
    {
        "company_name":           "DeskFit Professional Ltd",
        "address":                "7 King Street, Edinburgh, EH2 3AH",
        "website":                "https://www.deskfitpro.co.uk",
        "email":                  "bookings@deskfitpro.co.uk",
        "telephone":              "0131 555 2240",
        "main_category":          "Risk assessments",
        "subcategory":            "DSE assessments",
        "service_description":    "Individual and group DSE assessments for office environments. Assessors hold NEBOSH and Chartered Ergonomist credentials. Covers equipment setup, seating, lighting, glare and task rotation. Full written report per employee.",
        "pricing_amount":         "420.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/deskfit-professional",
    },
    {
        "company_name":           "ScreenSafe Occupational Health Ltd",
        "address":                "3 Broad Street, Bristol, BS1 2EL",
        "website":                "https://www.screensafeocc.co.uk",
        "email":                  "service@screensafeocc.co.uk",
        "telephone":              "0117 929 6650",
        "main_category":          "Risk assessments",
        "subcategory":            "DSE assessments",
        "service_description":    "DSE workstation assessment programme for employers with 10 to 1,000+ users. Includes self-assessment tool, assessor review, equipment specification report and compliance tracking dashboard. GDPR compliant data handling.",
        "pricing_amount":         "45.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/screensafe-occupational",
    },

    # Workplace safety audits
    {
        "company_name":           "Vigilance Safety Ltd",
        "address":                "18 St James Boulevard, Newcastle upon Tyne, NE1 4AX",
        "website":                "https://www.vigilancesafety.co.uk",
        "email":                  "audits@vigilancesafety.co.uk",
        "telephone":              "0191 261 8800",
        "main_category":          "Risk assessments",
        "subcategory":            "Workplace safety audits",
        "service_description":    "Independent workplace safety audits covering management systems, documentation, training records and physical workplace conditions. Scored against HSE and ISO 45001 benchmarks. Improvement roadmap included.",
        "pricing_amount":         "850.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/vigilance-safety",
    },
    {
        "company_name":           "TrueSafe Audit Services Ltd",
        "address":                "11 Market Street, Leeds, LS1 6DH",
        "website":                "https://www.truesafeaudit.co.uk",
        "email":                  "info@truesafeaudit.co.uk",
        "telephone":              "0113 245 7780",
        "main_category":          "Risk assessments",
        "subcategory":            "Workplace safety audits",
        "service_description":    "Structured safety management audits for all industry sectors. ISO 45001 gap analysis, HSE compliance checks and policy review included. Findings reported using a standardised scoring matrix with RAG status.",
        "pricing_amount":         "72.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/truesafe-audit",
    },
    {
        "company_name":           "Safeguard FM Consultants Ltd",
        "address":                "25 Cannon Street, London, EC4M 5TA",
        "website":                "https://www.safeguardfm.co.uk",
        "email":                  "audit@safeguardfm.co.uk",
        "telephone":              "020 7626 3300",
        "main_category":          "Risk assessments",
        "subcategory":            "Workplace safety audits",
        "service_description":    "FM-specific workplace safety audits covering building fabric, M&E plant, contractor management and emergency procedures. Suitable for estates of 5 to 500+ buildings. Benchmarking against sector peers available on request.",
        "pricing_amount":         "920.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/safeguard-fm",
    },
    {
        "company_name":           "ProAudit Safety Ltd",
        "address":                "9 Waterloo Place, Edinburgh, EH1 3BG",
        "website":                "https://www.proauditsafety.co.uk",
        "email":                  "team@proauditsafety.co.uk",
        "telephone":              "0131 226 4410",
        "main_category":          "Risk assessments",
        "subcategory":            "Workplace safety audits",
        "service_description":    "Comprehensive workplace safety audits for public sector and corporate clients. Includes documentation review, site walk-through, worker consultation and board-level summary report. Follow-up audit at 6 months included.",
        "pricing_amount":         "880.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/proaudit-safety",
    },

    # ═══════════════════════════════════════════════════════════════════════
    # ELECTRICITY
    # ═══════════════════════════════════════════════════════════════════════

    # PAT testing
    {
        "company_name":           "PlugSafe Electrical Ltd",
        "address":                "3 Clifton Road, Bristol, BS8 1AF",
        "website":                "https://www.plugsafeelectrical.co.uk",
        "email":                  "pat@plugsafeelectrical.co.uk",
        "telephone":              "0117 973 6640",
        "main_category":          "Electricity",
        "subcategory":            "PAT testing",
        "service_description":    "Portable appliance testing for offices, schools and commercial premises. All appliances tested to IET Code of Practice. Pass/fail labels applied to all items. Full asset register and certificate issued. Volume discounts available.",
        "pricing_amount":         "180.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/plugsafe-electrical",
    },
    {
        "company_name":           "VoltCheck Services Ltd",
        "address":                "27 London Road, Brighton, BN1 4JH",
        "website":                "https://www.voltcheckservices.co.uk",
        "email":                  "bookings@voltcheckservices.co.uk",
        "telephone":              "01273 841 200",
        "main_category":          "Electricity",
        "subcategory":            "PAT testing",
        "service_description":    "Annual PAT testing for up to 150 items per visit. NICEIC registered contractor. Detailed asset register provided with test results, retest dates and failed items highlighted. IT equipment, white goods and AV equipment all covered.",
        "pricing_amount":         "15.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/voltcheck-services",
    },
    {
        "company_name":           "CurrentSafe Compliance Ltd",
        "address":                "44 High Street, Swindon, SN1 3EP",
        "website":                "https://www.currentsafecompliance.co.uk",
        "email":                  "service@currentsafecompliance.co.uk",
        "telephone":              "01793 480 770",
        "main_category":          "Electricity",
        "subcategory":            "PAT testing",
        "service_description":    "Portable appliance testing with same-day labelling and digital report. Covers Class I and Class II appliances. NICEIC approved. All test data retained for 3 years on secure cloud platform accessible by client.",
        "pricing_amount":         "200.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/currentsafe-compliance",
    },
    {
        "company_name":           "EarthLine Testing Ltd",
        "address":                "6 Tollgate Road, Colchester, CO3 8AB",
        "website":                "https://www.earthlinetesting.co.uk",
        "email":                  "info@earthlinetesting.co.uk",
        "telephone":              "01206 591 100",
        "main_category":          "Electricity",
        "subcategory":            "PAT testing",
        "service_description":    "Portable appliance testing service for multi-site estates. Fixed price per item regardless of type. ECA member. Provides combined PAT and visual inspection report with recommended next test intervals based on equipment risk rating.",
        "pricing_amount":         "165.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/earthline-testing",
    },

    # EICR inspections
    {
        "company_name":           "CableCheck Electrical Ltd",
        "address":                "10 Granby Street, Leicester, LE1 1DJ",
        "website":                "https://www.cablecheckelectrical.co.uk",
        "email":                  "eicr@cablecheckelectrical.co.uk",
        "telephone":              "0116 254 3300",
        "main_category":          "Electricity",
        "subcategory":            "EICR inspections",
        "service_description":    "Electrical Installation Condition Reports (EICR) for commercial premises in accordance with BS 7671 (18th Edition). NICEIC approved. Full inspection of distribution boards, wiring, earthing and bonding. Remedial works quoted on same day.",
        "pricing_amount":         "450.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/cablecheck-electrical",
    },
    {
        "company_name":           "WireWise Inspections Ltd",
        "address":                "15 Victoria Road, Bournemouth, BH1 4RG",
        "website":                "https://www.wirewiseinspections.co.uk",
        "email":                  "survey@wirewiseinspections.co.uk",
        "telephone":              "01202 291 440",
        "main_category":          "Electricity",
        "subcategory":            "EICR inspections",
        "service_description":    "Fixed and periodic wiring inspection and testing for offices and commercial buildings. All inspectors are City & Guilds 2391 qualified. EICR certificate issued within 5 working days. Colour-coded condition report included.",
        "pricing_amount":         "38.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/wirewise-inspections",
    },
    {
        "company_name":           "PowerCheck Solutions Ltd",
        "address":                "8 Brunel Way, Slough, SL1 1XL",
        "website":                "https://www.powerchecksolutions.co.uk",
        "email":                  "compliance@powerchecksolutions.co.uk",
        "telephone":              "01753 521 880",
        "main_category":          "Electricity",
        "subcategory":            "EICR inspections",
        "service_description":    "Commercial EICR inspections carried out by NICEIC approved contractors. Full schedule of test results, observations and recommendations issued. Prioritised remedial works report provided. EV charger and solar PV systems also inspected.",
        "pricing_amount":         "490.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/powercheck-solutions",
    },
    {
        "company_name":           "CircuitAudit Ltd",
        "address":                "33 Kings Road, Windsor, SL4 2AQ",
        "website":                "https://www.circuitaudit.co.uk",
        "email":                  "inspect@circuitaudit.co.uk",
        "telephone":              "01753 860 110",
        "main_category":          "Electricity",
        "subcategory":            "EICR inspections",
        "service_description":    "Electrical installation condition reporting for single and multi-site clients. Inspection scope agreed in advance. Findings classified C1, C2 and C3 per BS 7671. Digital report with photographic evidence. Reinspection intervals advised.",
        "pricing_amount":         "420.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/circuitaudit",
    },

    # Emergency lighting electrical checks
    {
        "company_name":           "SafeGlow Electrical Ltd",
        "address":                "5 Deansgate, Manchester, M3 2FF",
        "website":                "https://www.safeglow-electrical.co.uk",
        "email":                  "emergency@safeglow-electrical.co.uk",
        "telephone":              "0161 834 7700",
        "main_category":          "Electricity",
        "subcategory":            "Emergency lighting electrical checks",
        "service_description":    "Electrical testing of emergency lighting circuits, self-contained luminaires and central battery systems. Compliant with BS 5266 and BS 7671. NICEIC registered. Includes annual 3-hour functional test and monthly flick-test log review.",
        "pricing_amount":         "350.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/safeglow-electrical",
    },
    {
        "company_name":           "ExitCircuit Services Ltd",
        "address":                "19 Frederick Street, Edinburgh, EH2 2EY",
        "website":                "https://www.exitcircuit.co.uk",
        "email":                  "testing@exitcircuit.co.uk",
        "telephone":              "0131 225 9910",
        "main_category":          "Electricity",
        "subcategory":            "Emergency lighting electrical checks",
        "service_description":    "Periodic electrical inspection and testing of emergency lighting installations. Covers self-contained, slave and maintained luminaires. Fault finding and lamp replacement included in contract. Compliance certificate issued after every visit.",
        "pricing_amount":         "30.00",
        "pricing_billing_period": "per_month",
        "terms_url":              "/terms/exitcircuit-services",
    },
    {
        "company_name":           "LitePath Compliance Ltd",
        "address":                "9 Charles Street, Cardiff, CF10 2GD",
        "website":                "https://www.litepathcompliance.co.uk",
        "email":                  "info@litepathcompliance.co.uk",
        "telephone":              "029 2039 6620",
        "main_category":          "Electricity",
        "subcategory":            "Emergency lighting electrical checks",
        "service_description":    "Emergency lighting electrical compliance service for commercial and public buildings. Annual inspections include circuit continuity testing, battery capacity checks and photometric measurement. ECA member with full insurance.",
        "pricing_amount":         "370.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/litepath-compliance",
    },
    {
        "company_name":           "BrightCircuit Testing Ltd",
        "address":                "14 Union Street, Aberdeen, AB10 1BD",
        "website":                "https://www.brightcircuittesting.co.uk",
        "email":                  "bookings@brightcircuittesting.co.uk",
        "telephone":              "01224 630 440",
        "main_category":          "Electricity",
        "subcategory":            "Emergency lighting electrical checks",
        "service_description":    "Emergency lighting electrical testing across Scotland and Northern England. Full BS 5266-1 compliance programme. Covers luminaire testing, maintained signage checks and battery replacement. All test records stored digitally.",
        "pricing_amount":         "340.00",
        "pricing_billing_period": "per_year",
        "terms_url":              "/terms/brightcircuit-testing",
    },
]


def seed():
    engine = get_engine()
    create_tables(engine)

    with Session(engine) as session:
        # Clear existing data before re-seeding
        existing = session.query(ServiceProvider).count()
        if existing > 0:
            print(f"  Clearing {existing} existing records...")
            session.query(ServiceProvider).delete()
            session.commit()

        providers = [ServiceProvider(**p) for p in PROVIDERS]
        session.add_all(providers)
        session.commit()

        count = session.query(ServiceProvider).count()
        print(f"\n  ✓ Seeded {count} service providers into agora_providers.db")

        # Summary by category
        from sqlalchemy import func
        results = (
            session.query(
                ServiceProvider.main_category,
                ServiceProvider.subcategory,
                func.count(ServiceProvider.id).label("n")
            )
            .group_by(ServiceProvider.main_category, ServiceProvider.subcategory)
            .order_by(ServiceProvider.main_category, ServiceProvider.subcategory)
            .all()
        )
        print()
        current_cat = None
        for cat, sub, n in results:
            if cat != current_cat:
                print(f"  {cat}")
                current_cat = cat
            print(f"    └─ {sub}: {n} providers")


if __name__ == "__main__":
    print("\n" + "=" * 50)
    print("  AGORA FM — Service Provider Seed Script")
    print("=" * 50)
    seed()
    print("\n" + "=" * 50 + "\n")
